/** 导演分类型 + 摄影参考片 — 由 build-data.mjs 合并进主库 */

export const directorCategories = [
  {
    id: 'director_sci_fi',
    label: '导演·科幻奇幻',
    items: [
      { zh: '雷德利·斯科特', en: 'Ridley Scott style', desc: '烟雾、强烈逆光、宏大工业机械、末日科幻美学' },
      { zh: '丹尼斯·维伦纽瓦', en: 'Denis Villeneuve style', desc: '极简巨物、大地色系、冷寂苍茫、科幻史诗感' },
      { zh: '克里斯托弗·诺兰', en: 'Christopher Nolan style', desc: '胶片质感、实景美学、宏大冷峻的时空宿命感' },
      { zh: '詹姆斯·卡梅隆', en: 'James Cameron style', desc: '极致的深蓝色调、硬核重工业机械、高对比数码锐度' },
      { zh: '乔治·米勒', en: 'George Miller style', desc: '极高饱和橙蓝对比、漫天沙尘、疯狂的动感与废土机械' },
      { zh: '沃卓斯基姐妹', en: 'The Wachowskis style', desc: '新好莱坞冷绿、黑客矩阵数字感、极速动态视觉' },
      { zh: '斯蒂芬·斯皮尔伯格', en: 'Steven Spielberg style', desc: '标志性镜头逆光炫光、充满冒险感的大气边缘光' },
      { zh: '郭帆', en: 'Frant Gwo style', desc: '重工业美学、中式宏大叙事、冷暖色调强烈碰撞' },
      { zh: '吕克·贝松', en: 'Luc Besson style', desc: '法式色彩斑斓、夸张视觉符号、高亢的动作动感' },
      { zh: '提姆·伯顿', en: 'Tim Burton style', desc: '哥特式微怪诞、黑白死寂、扭曲的线条与荒诞造型' },
      { zh: '吉尔莫·德尔·托罗', en: 'Guillermo del Toro style', desc: '黑暗童话、怪物美学、高对比饱和度、琥珀色与青色对立' },
      { zh: '亚历克斯·加兰', en: 'Alex Garland style', desc: '冰冷理性的硬核科幻、高科技极简几何、隐秘的自然吞噬' },
      { zh: '乔治·卢卡斯', en: 'George Lucas style', desc: '复古太空歌剧、粗糙的机械质感、广阔的异星地貌' },
      { zh: '特里·吉列姆', en: 'Terry Gilliam style', desc: '蒸汽朋克、扭曲的大广角、荒诞繁复的复古未来主义' },
      { zh: '庵野秀明', en: 'Hideaki Anno style', desc: '极具压迫感的电线杆几何构图、文字排版视觉、末日神圣感' },
      { zh: '保罗·范霍文', en: 'Paul Verhoeven style', desc: '高饱和血腥科幻、冷硬金属质感、讽刺性未来废土与肉体暴力美学' },
      { zh: '约瑟夫·科辛斯基', en: 'Joseph Kosinski style', desc: '极简对称构图、冷冽蓝灰数码质感、宏大空旷的未来废墟' },
      { zh: '邓肯·琼斯', en: 'Duncan Jones style', desc: '幽闭太空舱、低调冷光、理性孤独与存在主义科幻' },
      { zh: '理查德·凯利', en: 'Richard Kelly style', desc: '80年代复古霓虹、诡异梦境逻辑、末日寓言式超现实' },
      { zh: '亚历克斯·普罗亚斯', en: 'Alex Proyas style', desc: '哥特式未来都市、浓重阴影与雨夜、机械神话感' },
      { zh: '罗伯特·泽米吉斯', en: 'Robert Zemeckis style', desc: '流畅运动长镜头、温暖与冷科幻交织、经典好莱坞叙事光' },
      { zh: '史蒂文·索德伯格', en: 'Steven Soderbergh style', desc: '冷静克制的数码影像、太空孤寂的极简布光、疏离纪实感' },
      { zh: '詹姆斯·古恩', en: 'James Gunn style', desc: '高饱和波普科幻、复古金曲与鲜艳色块、怪诞幽默的宇宙奇观' },
      { zh: '塔伊加·维迪提', en: 'Taika Waititi style', desc: '高饱和奇幻色彩、手持温暖幽默、史诗与荒诞并置' },
      { zh: '莱恩·约翰逊', en: 'Rian Johnson style', desc: '复古未来主义、锐利构图、悬疑叙事与类型片视觉游戏' },
      { zh: '彼得·威尔', en: 'Peter Weir style', desc: '超现实日常、刺眼人造阳光、存在主义寓言的通透影像' },
      { zh: '弗朗西斯·劳伦斯', en: 'Francis Lawrence style', desc: '末世废土冷暖对比、压迫性广角、商业史诗级场面调度' },
      { zh: '马特·里夫斯', en: 'Matt Reeves style', desc: '阴郁雨夜都市、低调光与霓虹反射、沉重写实的黑暗氛围' },
      { zh: '安德鲁·斯坦顿', en: 'Andrew Stanton style', desc: '温暖童话科幻、柔和逆光、宏大宇宙中的孤独诗意' },
      { zh: '安德鲁·尼科尔', en: 'Andrew Niccol style', desc: '冷冽极简未来社会、高反差建筑线条、存在主义科幻美学' }
    ]
  },
  {
    id: 'director_thriller',
    label: '导演·悬疑犯罪',
    items: [
      { zh: '大卫·芬奇', en: 'David Fincher style', desc: '极低调光、墨绿/青蓝暗部、极其精准克制的机械机位' },
      { zh: '阿尔弗雷德·希区柯克', en: 'Alfred Hitchcock style', desc: '经典好莱坞布光、强烈的眼神特写、充满心理暗示的悬疑构图' },
      { zh: '昆汀·塔伦蒂诺', en: 'Quentin Tarantino style', desc: '暴力色彩、复古胶片、低角度仰拍（后备箱视角）、邪典感' },
      { zh: '朴赞郁', en: 'Park Chan-wook style', desc: '极致病态的美学、高饱和度诡异色彩、巴洛克式繁复构图' },
      { zh: '奉俊昊', en: 'Bong Joon-ho style', desc: '阶级隐喻的空间对立构图、潮湿阴暗的色调、冷酷的社会纪实' },
      { zh: '马丁·斯科塞斯', en: 'Martin Scorsese style', desc: '街头纪实、快速剪辑感、霓虹闪烁的深夜纽约、浓郁罪恶感' },
      { zh: '罗曼·波兰斯基', en: 'Roman Polanski style', desc: '幽闭恐惧的空间构图、冷峻克制的色调、心理惊悚感' },
      { zh: '罗伯特·罗德里格兹', en: 'Robert Rodriguez style', desc: '粗粝、漫画面感高饱和、狂野的墨西哥废土与枪火' },
      { zh: '迈克尔·曼', en: 'Michael Mann style', desc: '深夜城市的数码高光、冷蓝色调、写实的枪战火光' },
      { zh: '丹尼斯·维伦纽瓦(犯罪)', en: 'Denis Villeneuve crime style', desc: '烈日下的压抑阴影、尘土飞扬、令人窒息的静态张力' },
      { zh: '曹保平', en: 'Cao Baoping style', desc: '粗粝的现实主义、高频手持晃动、燥热而焦虑的色调' },
      { zh: '刁亦男', en: 'Diao Yinan style', desc: '东北重工业废墟、绚丽而廉价的霓虹、冷酷的暗夜' },
      { zh: '大卫·林奇', en: 'David Lynch style', desc: '梦境超现实、诡异的红色天鹅绒、暗黑扭曲的心理暗示' },
      { zh: '彭浩翔', en: 'Pang Ho-cheung style', desc: '都市冷幽默、干净利落的现代构图、略带诡异的色调' },
      { zh: '罗宏镇', en: 'Na Hong-jin style', desc: '极致的潮湿、泥泞、暴雨、压抑绝望的暗黑现实主义' },
      { zh: '科恩兄弟', en: 'Coen Brothers style', desc: '荒诞黑色幽默、广角畸变、荒凉公路与冷冽命运感' },
      { zh: '布莱恩·德·帕尔玛', en: 'Brian De Palma style', desc: '分割画面、眩晕变焦、歌剧式悬疑与窥视构图' },
      { zh: '迈克尔·哈内克', en: 'Michael Haneke style', desc: '冰冷固定机位、毫无预警的暴力、中产阶级空虚的极简影像' },
      { zh: '西德尼·吕美特', en: 'Sidney Lumet style', desc: '法庭与都市密闭空间、写实布光、道德困境的压迫构图' },
      { zh: '威廉·弗莱德金', en: 'William Friedkin style', desc: '粗粝纪实、手持追逐、极端反差与邪典惊悚张力' },
      { zh: '尼古拉斯·温丁·雷弗恩', en: 'Nicolas Winding Refn style', desc: '霓虹粉蓝、极简构图、慢动作暴力与合成器美学' },
      { zh: '麦兆辉', en: 'Alan Mak style', desc: '港式卧底悬疑、冷调都市夜景、镜像与身份分裂构图' },
      { zh: '庄文强', en: 'Felix Chong style', desc: '精密叙事空间、电梯与天台对峙、都市谍影的冷峻光' },
      { zh: '林岭东', en: 'Ringo Lam style', desc: '火爆警匪动作、粗粝手持、九龙城寨式的压迫烟火气' },
      { zh: '管虎', en: 'Guan Hu style', desc: '地下迷宫式空间、粗颗粒纪实、中国城市底层的幽闭焦虑' },
      { zh: '关锦鹏', en: 'Stanley Kwan style', desc: '华丽怀旧色调、女性凝视、暧昧光影中的都市情欲' },
      { zh: '阿斯哈·法拉哈迪', en: 'Asghar Farhadi style', desc: '克制的中景对话、家庭空间里的道德困局、自然光下的压抑' },
      { zh: '德里克·斯安西斯', en: 'Derek Cianfrance style', desc: '粗粝16mm质感、手持跟拍、悲剧宿命的长镜头呼吸感' },
      { zh: '托德·菲利普斯', en: 'Todd Phillips style', desc: '病态青绿哥谭、沉重胶片颗粒、边缘人物的癫狂纪实' },
      { zh: '游乃海', en: 'Yau Nai-hoi style', desc: '银河映像式冷幽默、精准走位构图、都市猎奇的黑色荒诞' },
      { zh: '乔纳森·戴米', en: 'Jonathan Demme style', desc: '直视镜头的心理压迫、亲密特写、温暖与恐怖并存' },
      { zh: '达伦·阿罗诺夫斯基', en: 'Darren Aronofsky style', desc: '手持眩晕、极端特写、心理崩溃的压迫性剪辑节奏' },
      { zh: '约翰·休斯顿', en: 'John Huston style', desc: '经典黑色电影低调光、百叶窗阴影、硬汉命运式构图' },
      { zh: '比利·怀尔德(黑色)', en: 'Billy Wilder noir style', desc: '辛辣黑色幽默、高反差黑白、都市欲望与道德灰区' }
    ]
  },
  {
    id: 'director_art',
    label: '导演·文艺情感',
    items: [
      { zh: '王家卫', en: 'Wong Kar-wai style', desc: '霓虹、慢速快门动感模糊、抽帧、充满暧昧与情绪的流金' },
      { zh: '韦斯·安德森', en: 'Wes Anderson style', desc: '绝对对称构图、高饱和马卡龙色、玩味幽默的平面化视觉' },
      { zh: '岩井俊二', en: 'Shunji Iwai style', desc: '极度柔和的白高调、日系逆光、朦胧唯美的青春感' },
      { zh: '毕赣', en: 'Bi Gan style', desc: '凯里梦境、潮湿长镜头、魔幻现实主义的诗意绿色' },
      { zh: '滨口龙介', en: 'Ryusuke Hamaguchi style', desc: '克制平静的日常构图、通透的自然光、绵密的空气感' },
      { zh: '是枝裕和', en: 'Hirokazu Kore-eda style', desc: '温柔克制的家庭视角、温暖明亮的自然光、生活碎片的细腻质感' },
      { zh: '汤姆·福特', en: 'Tom Ford style', desc: '极致的时尚奢华、教科书级的色彩搭配、对称高贵的人像' },
      { zh: '索菲亚·科波拉', en: 'Sofia Coppola style', desc: '少女迷茫感、低饱和粉嫩色调、阳光洒落在发丝的轻盈感' },
      { zh: '伍迪·艾伦', en: 'Woody Allen style', desc: '温暖的知识分子黄调、欧洲城市复古风光、话痨式的街头漫步' },
      { zh: '阿莫多瓦', en: 'Pedro Almodovar style', desc: '极其浓烈大胆的红蓝绿撞色、女性主义、巴洛克式热情' },
      { zh: '卢卡·瓜达尼诺', en: 'Luca Guadagnino style', desc: '意大利夏日的炽热阳光、复古庄园、汗水与荷尔蒙的流动质感' },
      { zh: '贾木许', en: 'Jim Jarmusch style', desc: '摇滚青年的不羁、极简黑白或迷幻夜色、疏离冷酷的诗意' },
      { zh: '米歇尔·贡德里', en: 'Michel Gondry style', desc: '手工感怪诞梦境、手工拼贴风、奇幻而浪漫的视觉想象' },
      { zh: '理查德·林克莱特', en: 'Richard Linklater style', desc: '真实的流逝时间感、自然流淌的黄昏与黎明微光' },
      { zh: '娄烨', en: 'Lou Ye style', desc: '极度失焦的手持雨夜、潮湿的情欲、紫幻与迷茫的城市边缘' },
      { zh: '许鞍华', en: 'Ann Hui style', desc: '市井人文关怀、朴素克制的纪实镜头、平静中的力量' },
      { zh: '贾樟柯', en: 'Jia Zhangke style', desc: '时代阵痛的县城纪实、粗粝的DV/早期数码感、纪实符号' },
      { zh: '侯孝贤', en: 'Hou Hsiao-hsien style', desc: '极深空间的长镜头、固定机位、空灵的东方留白与蝉鸣感' },
      { zh: '泰伦斯·马力克', en: 'Terrence Malick style', desc: '广角自然光、飘逸手持、诗意旁白式的神圣日常与万物凝视' },
      { zh: '保罗·托马斯·安德森', en: 'Paul Thomas Anderson style', desc: '超长镜头调度、油画般浓郁色彩、美国梦的癫狂与孤独' },
      { zh: '阿方索·卡隆', en: 'Alfonso Cuaron style', desc: '流畅长镜头、真实光影、宏大历史中的个体漂泊感' },
      { zh: '亚历杭德罗·冈萨雷斯', en: 'Alejandro Gonzalez Inarritu style', desc: '手持纪实、多线叙事、冷冽自然光下的生存与救赎' },
      { zh: '蔡明亮', en: 'Tsai Ming-liang style', desc: '极简固定长镜头、潮湿台北、孤独身体与都市空间的疏离' },
      { zh: '洪尚秀', en: 'Hong Sang-soo style', desc: '自然光对话、轻微醉酒的真实感、日常中的微妙情感波动' },
      { zh: '维姆·文德斯', en: 'Wim Wenders style', desc: '公路电影漂泊感、清冷色调、异乡人的诗意孤独' },
      { zh: '巴里·詹金斯', en: 'Barry Jenkins style', desc: '月光下的蓝紫色调、细腻特写、沉默中的情感涌动' },
      { zh: '新海诚', en: 'Makoto Shinkai style', desc: '极致唯美的天空与光线、数码细腻质感、青春距离的透明色' },
      { zh: '今敏', en: 'Satoshi Kon style', desc: '现实与梦境跳接、快速蒙太奇、都市心理的眩晕视觉' },
      { zh: '达米恩·查泽雷', en: 'Damien Chazelle style', desc: '经典好莱坞歌舞光影、梦幻柔光、激情与幻灭的对比' },
      { zh: '田壮壮', en: 'Tian Zhuangzhuang style', desc: '苍茫草原史诗、自然光下的历史厚重、东方视野的辽阔留白' },
      { zh: '张艺谋(文艺)', en: 'Zhang Yimou art style', desc: '浓烈东方色彩、大色块构图、民俗仪式化的视觉奇观' },
      { zh: '霍建起', en: 'Huo Jianqi style', desc: '唯美江南水墨感、柔和散射光、古典诗意的慢节奏' },
      { zh: '顾长卫', en: 'Gu Changwei style', desc: '时代肖像式特写、粗粝胶片质感、小人物命运的沉静凝视' },
      { zh: '张大磊', en: 'Zhang Dalei style', desc: '90年代东北怀旧、昏黄室内光、缓慢流淌的青春期记忆' },
      { zh: '李沧东', en: 'Lee Chang-dong style', desc: '冷冽社会纪实、突然爆发的暴力、沉默压抑的韩国底层光影' },
      { zh: '张律', en: 'Zhang Lu style', desc: '中朝边境诗意、长镜头静默、异乡漂泊的冷冽自然光' }
    ]
  },
  {
    id: 'director_action',
    label: '导演·动作战争',
    items: [
      { zh: '扎克·施奈德', en: 'Zack Snyder style', desc: '高反差、重颗粒、暗黑、油画雕塑般的神话肌肉线条' },
      { zh: '麦克·贝', en: 'Michael Bay style', desc: '标志性爆炸黄昏低角度环绕运镜（贝式弧线）、极致碎裂感' },
      { zh: '梅尔·吉布森', en: 'Mel Gibson style', desc: '惨烈的原始战场、血腥泥泞的宏大史诗感、硬核纪实' },
      { zh: '吴宇森', en: 'John Woo style', desc: '双枪、飞鸽、标志性慢动作、极具浪漫主义的枪战火光' },
      { zh: '杜琪峰', en: 'Johnnie To style', desc: '极强的站位空间构图、硬核黑帮黑白光影、冷酷的宿命感' },
      { zh: '查德·斯塔赫尔斯基', en: 'Chad Stahelski style', desc: '《疾速追杀》式极致绚丽霓虹色彩、现代动作格斗冷冽感' },
      { zh: '盖·里奇', en: 'Guy Ritchie style', desc: '极速快慢转换、多线索碎片化视觉、英伦复古痞子风' },
      { zh: '埃德加·赖特', en: 'Edgar Wright style', desc: '极快视听节奏、卡点转场、充满漫画色彩的波普动作美学' },
      { zh: '徐克', en: 'Tsui Hark style', desc: '天马行空的武侠动感、倾斜险峻的构图、诡谲的色彩' },
      { zh: '张艺谋(动作)', en: 'Zhang Yimou wuxia style', desc: '极致的单色系武侠（如大红、纯黑白墨画）、视觉奇观' },
      { zh: '姜文', en: 'Jiang Wen style', desc: '雄性荷尔蒙爆发、阳光暴晒的炙热感、荒诞而疯狂的动态' },
      { zh: '袁和平', en: 'Yuen Woo-ping style', desc: '硬核硬桥硬马传统功夫视觉、凌厉的动作线条感' },
      { zh: '林超贤', en: 'Dante Lam style', desc: '现代军事硬核工业感、爆炸烟尘、极速跟拍' },
      { zh: '彼得·杰克逊', en: 'Peter Jackson style', desc: '新西兰宏大中土世界、奇幻史诗交响感、震撼的千军万马' },
      { zh: '萨姆·门德斯', en: 'Sam Mendes style', desc: '伪一镜到底、精准完美的战争构图、冷峻克制（《1917》）' },
      { zh: '成龙', en: 'Jackie Chan style', desc: '创意环境打斗、广角清晰景深、幽默肢体与工业现场的真实质感' },
      { zh: '甄子丹', en: 'Donnie Yen style', desc: '凌厉近身格斗、快速剪辑与长镜结合、硬朗冷峻的动作线条' },
      { zh: '叶伟信', en: 'Wilson Yip style', desc: '咏春写实格斗、阴雨香港色调、沉稳凌厉的动作叙事' },
      { zh: '约翰·麦克蒂尔南', en: 'John McTiernan style', desc: '经典80年代动作、低角度硬汉构图、封闭空间的紧张压迫' },
      { zh: '保罗·格林格拉斯', en: 'Paul Greengrass style', desc: '剧烈手持抖动、极速剪辑、纪录片式的临场动作混乱' },
      { zh: '罗兰·艾默里奇', en: 'Roland Emmerich style', desc: '毁灭级大场面、金黄黄昏光、全球灾难的宏大广角' },
      { zh: '陈木胜', en: 'Benny Chan style', desc: '港式硬桥硬马、火爆追车、都市天际线下的凌厉动作' },
      { zh: '吴京', en: 'Wu Jing style', desc: '军事硬汉美学、高饱和战场烟尘、民族英雄式的热血广角' },
      { zh: '郑保瑞', en: 'Soi Cheang style', desc: '暗黑神话动作、浓重阴影、怪诞暴力的东方奇幻视觉' },
      { zh: '刘伟强', en: 'Andrew Lau style', desc: '快速剪辑枪战、冷调都市夜景、港式商业大片的凌厉节奏' },
      { zh: '北野武', en: 'Takeshi Kitano style', desc: '静穆长镜头与突发暴力、冷峻海面、极简构图的残酷美学' },
      { zh: '押井守', en: 'Mamoru Oshii style', desc: '赛博朋克冷调、哲学式慢节奏、机械与灵魂的沉重氛围' },
      { zh: '唐季礼', en: 'Stanley Tong style', desc: '成龙式国际动作、明亮清晰、跨国场景的冒险大片感' },
      { zh: '西蒙·韦斯特', en: 'Simon West style', desc: '90年代动作黄金期、慢动作爆炸、硬朗男性荷尔蒙光' },
      { zh: '安东尼·福奎阿', en: 'Antoine Fuqua style', desc: '写实警匪动作、冷调都市、Training Day式阴暗光影' }
    ]
  },
  {
    id: 'director_masters',
    label: '导演·影史殿堂',
    items: [
      { zh: '斯坦利·库布里克', en: 'Stanley Kubrick style', desc: '极致的一点透视对称构图、冷酷的理智感、神圣未来主义' },
      { zh: '安德烈·塔可夫斯基', en: 'Andrei Tarkovsky style', desc: '圣像画般的质感、水与火的诗意隐喻、极其缓慢的灵性长镜头' },
      { zh: '黑泽明', en: 'Akira Kurosawa style', desc: '完美的风雨雷电自然调动、充满戏剧张力的多人物群体构图' },
      { zh: '小津安二郎', en: 'Yasujiro Ozu style', desc: '标志性榻榻米低机位、永远固定的视线、克制的东方家庭' },
      { zh: '宫崎骏', en: 'Hayao Miyazaki style', desc: '治愈系手绘水彩画风、充满生机的翠绿与瓦蓝、久石让式童话' },
      { zh: '费德里科·费里尼', en: 'Federico Fellini style', desc: '荒诞游行、马戏团狂欢、梦境与现实模糊的意大利世俗美学' },
      { zh: '英格玛·伯格曼', en: 'Ingmar Bergman style', desc: '极高反差的人物面部特写（审视灵魂）、北欧极度冰冷荒凉' },
      { zh: '弗朗西斯·科波拉', en: 'Francis Ford Coppola style', desc: '顶级的油画质感低调光、黑帮帝国的史诗黄金色调' },
      { zh: '让·吕克·戈达尔', en: 'Jean-Luc Godard style', desc: '法国新浪潮跳接、打破第四面墙、极具政治与拼贴艺术感' },
      { zh: '弗朗索瓦·特吕弗', en: 'Francois Truffaut style', desc: '新浪潮温柔奔跑、纪实与诗意并存的法式浪漫' },
      { zh: '阿巴斯', en: 'Abbas Kiarostami style', desc: '车内视角的流动风景、质朴的伊朗乡村大地色、真假虚实' },
      { zh: '赛尔乔·莱昂内', en: 'Sergio Leone style', desc: '极致的眼睛大特写、广阔的通天大远景、西部荒野肃杀感' },
      { zh: '沟口健二', en: 'Kenji Mizoguchi style', desc: '一景一镜的卷轴式横向平移长镜头、古典日本女性悲剧美' },
      { zh: '西奥·安哲罗普洛斯', en: 'Theo Angelopoulos style', desc: '希腊连绵的阴天雾气、历史废墟上的孤独漫步、漫长冬日' },
      { zh: '贝纳尔多·贝托鲁奇', en: 'Bernardo Bertolucci style', desc: '穿透宫殿的绝美自然光影、紫禁城流金、时代史诗' },
      { zh: '克日什托夫·基斯洛夫斯基', en: 'Krzysztof Kieslowski style', desc: '极致的滤镜色彩隐喻（红白蓝）、玻璃折射、命运交织' },
      { zh: '查理·卓别林', en: 'Charlie Chaplin style', desc: '经典默片黑白、固定中景、滑稽动作与悲凉内核碰撞' },
      { zh: '萨蒂亚吉特·雷伊', en: 'Satyajit Ray style', desc: '质朴隽永的印度人文纪实、波澜不惊的诗意日常' },
      { zh: '奥逊·威尔斯', en: 'Orson Welles style', desc: '深焦镜头、低角度仰拍、权力与命运的戏剧化光影' },
      { zh: '比利·怀尔德', en: 'Billy Wilder style', desc: '辛辣机智的都市光影、经典好莱坞布光、人性灰度的精准构图' },
      { zh: '约翰·福特', en: 'John Ford style', desc: '纪念碑式西部远景、门框构图、美国神话的苍茫大地' },
      { zh: '大卫·里恩', en: 'David Lean style', desc: '史诗级宽银幕、沙漠与铁道的宏大构图、古典浪漫主义' },
      { zh: '路易斯·布努埃尔', en: 'Luis Bunuel style', desc: '超现实梦境、荒诞讽刺、中产阶级伪善的冷静揭露' },
      { zh: '罗伯特·布列松', en: 'Robert Bresson style', desc: '极简克制、机械精准的动作、灵魂拷问式的冷峻特写' },
      { zh: '维托里奥·德·西卡', en: 'Vittorio De Sica style', desc: '新现实主义街头光影、非职业演员的真实质感、悲悯的人文' },
      { zh: '让·雷诺阿', en: 'Jean Renoir style', desc: '流畅深焦长镜头、贵族沙龙的自然光、人性流动的优雅' },
      { zh: '卡罗尔·里德', en: 'Carol Reed style', desc: '倾斜构图、战后维也纳的阴郁光影、经典黑色悬疑' },
      { zh: '迈克尔·鲍威尔', en: 'Michael Powell style', desc: '浓烈色彩幻想、歌剧式视觉、欲望与恐惧的华丽交织' },
      { zh: '阿涅斯·瓦尔达', en: 'Agnes Varda style', desc: '轻盈纪实、女性视角、生活细节中的政治与诗意' },
      { zh: '今村昌平', en: 'Shohei Imamura style', desc: '粗粝原始的生命力、动物性与欲望、日本底层的泥土质感' },
      { zh: '大岛渚', en: 'Nagisa Oshima style', desc: '政治反叛、大胆情欲、打破禁忌的凌厉构图' },
      { zh: '成濑巳喜男', en: 'Mikio Naruse style', desc: '女性命运的长镜头、低调室内光、隐忍克制的日本家庭' },
      { zh: '谢尔盖·帕拉杰诺夫', en: 'Sergei Parajanov style', desc: '民族图腾式构图、静止画框美学、超现实的民俗色彩' },
      { zh: '卡尔·西奥多·德莱叶', en: 'Carl Theodor Dreyer style', desc: '极端面部特写、白墙神圣光、灵魂受难的静穆影像' },
      { zh: '罗伯特·奥特曼', en: 'Robert Altman style', desc: '重叠对话、变焦长镜头、群像式的美国社会切片' },
      { zh: '沃纳·赫尔佐格', en: 'Werner Herzog style', desc: '疯狂与自然的对抗、极端环境、存在主义的荒凉史诗' },
      { zh: '弗里茨·朗', en: 'Fritz Lang style', desc: '德国表现主义阴影、几何都市、命运与技术的冷酷视觉' },
      { zh: '卢基诺·维斯康蒂', en: 'Luchino Visconti style', desc: '贵族式华丽运镜、历史史诗、衰落美学的浓郁质感' },
      { zh: '劳伦斯·奥利弗', en: 'Laurence Olivier style', desc: '莎士比亚戏剧光影、舞台化构图、古典悲剧的庄重影像' },
      { zh: '路易斯·马姆', en: 'Louis Malle style', desc: '私密的人物凝视、自然光下的道德暧昧、法式与美式交织的纪实诗意' }
    ]
  },
  {
    id: 'director_chinese',
    label: '导演·华语新锐',
    items: [
      { zh: '杨德昌', en: 'Edward Yang style', desc: '冰冷克制的台北都市空间、高处俯瞰、理性知识分子的审视' },
      { zh: '宁浩', en: 'Ning Hao style', desc: '疯狂的黑色幽默、多线索剪辑视觉、市井小人物的躁动' },
      { zh: '陆川', en: 'Lu Chuan style', desc: '纪实手持、高反差颗粒、苍凉大气的无人区/历史现场' },
      { zh: '乌尔善', en: 'Wuershan style', desc: '极尽奢华的东方暗黑魔幻、重工业特效、神话雕塑美学' },
      { zh: '魏德圣', en: 'Wei Te-sheng style', desc: '台湾本土史诗、野性自然的绿色密林、浪漫的土地悲歌' },
      { zh: '程耳', en: 'Cheng Er style', desc: '极度强迫症的对称构图、优雅克制的腔调、高级的黑色幽默' },
      { zh: '文牧野', en: 'Wen Muye style', desc: '极具社会痛点的通俗纪实、充满烟火气的暖色调、平民英雄感' },
      { zh: '万玛才旦', en: 'Pema Tseden style', desc: '寂静的西藏藏地美学、魔幻现实与藏地日常、荒凉高原' },
      { zh: '魏书钧', en: 'Wei Shujun style', desc: '荒诞戏谑的元电影视角、复古粗粝的胶片感、青年反叛' },
      { zh: '忻钰坤', en: 'Xin Yukun style', desc: '烧脑的悬疑时空解构、中国北方农村的宿命感与压抑' },
      { zh: '周星驰', en: 'Stephen Chow style', desc: '夸张漫画无厘头、小人物的廉价斑斓色彩、笑中带泪的草根' },
      { zh: '李安', en: 'Ang Lee style', desc: '东方古典温良恭俭让、西方戏剧冲突、通透儒雅的视觉平衡' },
      { zh: '陈凯歌(早期)', en: 'Chen Kaige classic style', desc: '浓郁的黄土地史诗、京剧舞台式华丽悲剧布光' },
      { zh: '李玉', en: 'Li Yu style', desc: '女性身体与都市困境、粗粝手持、压抑而炽热的现实主义' },
      { zh: '李少红', en: 'Li Shaohong style', desc: '古典深宅大院、诡异红绿布光、女性命运的心理空间' },
      { zh: '邵艺辉', en: 'Shao Yihui style', desc: '都市女性喜剧、明亮生活质感、上海弄堂的烟火与幽默' },
      { zh: '文晏', en: 'Vivian Qu style', desc: '少女视角的社会隐痛、自然光纪实、沉默而锋利的女性凝视' },
      { zh: '滕丛丛', en: 'Teng Congcong style', desc: '女性公路诗意、辽阔自然光、中年觉醒的沉静影像' },
      { zh: '薛晓路', en: 'Xue Xiaolu style', desc: '都市浪漫轻喜剧、明亮通透、中产生活的温暖质感' },
      { zh: '张艾嘉', en: 'Sylvia Chang style', desc: '温柔家庭叙事、自然光下的代际情感、细腻的生活流' },
      { zh: '赵婷', en: 'Chloe Zhao style', desc: '广袤西部自然光、诗意纪实、流浪者与美国荒野的静默' },
      { zh: '冯小刚', en: 'Feng Xiaogang style', desc: '京味喜剧贺岁、暖黄怀旧色调、市井幽默与时代变迁' },
      { zh: '路阳', en: 'Lu Yang style', desc: '东方奇幻史诗、浓重暗调、历史与江湖的华丽视觉' },
      { zh: '大鹏', en: 'Dapeng style', desc: '小镇青年纪实、粗粝真实、喜剧外壳下的悲凉内核' },
      { zh: '饶晓志', en: 'Rao Xiaozhi style', desc: '荒诞喜剧、戏剧舞台感、小人物绝境中的黑色幽默' },
      { zh: '韩寒', en: 'Han Han style', desc: '公路青春、明亮海岸光、文艺青年的漂泊与怀旧' },
      { zh: '蔡尚君', en: 'Cai Shangjun style', desc: '边境黑色悬疑、冷冽荒原、人性贪婪的粗粝影像' },
      { zh: '黄建新', en: 'Huang Jianxin style', desc: '都市荒诞讽刺、平实布光、中国转型期的社会寓言' },
      { zh: '张扬', en: 'Zhang Yang style', desc: '西藏灵性叙事、纯净自然光、信仰与生命的诗意长镜' },
      { zh: '王小帅', en: 'Wang Xiaoshu style', desc: '时代记忆、灰调城市、青春与历史交织的纪实诗意' }
    ]
  }
];

export const cinematographyCategory = {
  id: 'cinematography',
  label: '摄影与参考片',
  items: [
    { zh: '《银翼杀手2049》', en: 'Blade Runner 2049 cinematography', desc: '罗杰·狄金斯。极致极简几何、雾霾金黄色、死寂霓虹、容积光束' },
    { zh: '《沙丘》', en: 'Dune 2026 cinematography', desc: '灰度极高的极简巨物、漫天沙尘黄、冷冽暗部、史诗级画幅' },
    { zh: '《阿凡达》', en: 'Avatar 2009 cinematography', desc: '极致饱满的潘多拉荧光、深邃冷蓝色调、数码立体通透度' },
    { zh: '《星际穿越》', en: 'Interstellar cinematography', desc: '65mm IMAX胶片质感、冷峻写实的深空黑、微弱温暖的舱内光' },
    { zh: '《疯狂麦克斯4》', en: 'Mad Max Fury Road style', desc: '极致过饱和橙蓝对比、烈日灼烧感、高帧率抓拍、速度线条' },
    { zh: '《黑客帝国》', en: 'The Matrix green tint style', desc: '标志性矩阵冷绿调、高对比度、皮革与墨镜的高光质感' },
    { zh: '《地心引力》', en: 'Gravity 2013 cinematography', desc: '卢贝兹基式极致长镜头、刺眼真实太阳光、冷酷无垠的地球弧线' },
    { zh: '《魔戒》', en: 'Lord of the Rings cinematography', desc: '古典新西兰奇幻史诗、温暖霍比特金光与冷酷魔多黑对比' },
    { zh: '《创：战纪》', en: 'TRON Legacy aesthetic', desc: '极简纯黑背景、极高饱和高亮发光霓虹线条、硬核电子科技' },
    { zh: '《流浪地球》', en: 'The Wandering Earth visual', desc: '重工业机械风、巨型行星发动机火焰、冰封地表冷蓝死寂' },
    { zh: '《教父》', en: 'The Godfather cinematography', desc: '戈登·威利斯暗黑之神色调。极致低调光、顶部深邃阴影、暖油画黄' },
    { zh: '《小丑》', en: 'Joker 2019 cinematography', desc: '压抑的哥谭青绿与病态橘黄、重胶片颗粒、边缘人物的孤独宿命' },
    { zh: '《七宗罪》', en: 'Se7en 1995 cinematography', desc: '永远下雨的阴郁城市、手电筒硬光打破极暗、漂浮的空气尘埃颗粒' },
    { zh: '《极速追杀》', en: 'John Wick neon noir visual', desc: '现代 Neon-Noir。极致绚丽的紫红、青蓝饱和高光' },
    { zh: '《花样年华》', en: 'In the Mood for Love style', desc: '李屏宾。极致暧昧的狭窄空间构图、暗淡摇曳的灯光、旗袍艳丽' },
    { zh: '《白日焰火》', en: 'Black Coal, Thin Ice style', desc: '刁亦男美学。中国北方冰天雪地、廉价刺眼的迪厅霓虹、冷酷纪实' },
    { zh: '《大红灯笼高高挂》', en: 'Raise the Red Lantern style', desc: '极致中式对称深宅大院、刺眼诡异的红灯笼光、高反差冷色屋顶' },
    { zh: '《刺客聂隐娘》', en: 'The Assassin 2015 visual', desc: '极其克制的东方微光胶片感、烛光穿透层层薄纱、古典山水画留白' },
    { zh: '《老无所依》', en: 'No Country for Old Men visual', desc: '德州烈日暴晒的枯黄、孤独漫长的公路、死寂而干净的阴影' },
    { zh: '《囚徒》', en: 'Prisoners 2013 cinematography', desc: '阴冷多雨的美国小镇、阴天微弱散射光、令人窒息的冷灰白调' },
    { zh: '《布达佩斯大饭店》', en: 'The Grand Budapest Hotel style', desc: '韦斯·安德森巅峰。粉红与柔蓝、极致中轴对称、微型画般的复古' },
    { zh: '《天使爱美丽》', en: 'Amelie 2001 cinematography', desc: '极度浓烈温暖的复古红绿撞色、巴黎浪漫超现实幻想、高饱和' },
    { zh: '《情书》', en: 'Love Letter 1995 visual', desc: '岩井俊二标志性日系白高调、北海道漫天大雪、温柔的逆光边缘' },
    { zh: '《请以你的名字呼唤我》', en: 'Call Me by Your Name visual', desc: '意大利夏日炽热阳光、蝉鸣感的通透自然光、慵懒的复古胶片感' },
    { zh: '《爱乐之城》', en: 'La La Land cinematography', desc: '经典好莱坞歌舞片流金黄昏、紫色星空、梦幻柔光镜、聚光灯追光' },
    { zh: '《罗马》', en: 'Roma 2018 cinematography', desc: '阿方索自摄。极致通透的65mm黑白超广角、无限空间深度与细节' },
    { zh: '《海边的曼彻斯特》', en: 'Manchester by the Sea style', desc: '冰冷残酷的冬日海滨冷蓝、无反差的惨白天空、克制压抑的平静' },
    { zh: '《生命之树》', en: 'The Tree of Life style', desc: '卢贝兹基全自然光。极度低角度广角逆光、神圣飘逸的流动感' },
    { zh: '《重庆森林》', en: 'Chungking Express style', desc: '刘伟强手持、慢速快门抽帧、快餐店霓虹与迷茫' },
    { zh: '《悲情城市》', en: 'A City of Sadness style', desc: '侯孝贤经典。深沉静穆的远景长镜头、自然光自然消逝的悲凉' }
  ]
};
